Feature/allow duplicates
no10ds/rapid pull request #104
Opened 2024-11-25 12:06 UTC by Jarek-Rolski

New attribute allow_duplicates defines if column allows duplicated values.

- API, SDK and UI are updated.
- Validation method for schema upload throws error if any column forbids duplicates and overwrite behaviour is APPEND.
- Validation method for dataset upload ignores null values in column.
- Error message for dataset upload returns columns names with duplicated values.
- Default attribute value is "True"
- Test for schema and dataset upload with allow_duplicates is passed.

I updated UI "jest" tests with new attribute. I didn't add any new more detailed test checking how attribute works in UI because "jest" and "playwright" UI tests in repository do not check such details.

2025-05-06 08:32 UTC, MotwaniM commented on api/api/application/services/schema_infer_service.py
> +                allow_duplicates=True
Do we want to default this to being true?

2025-05-06 16:21 UTC, MotwaniM requested changes
This looks good and very helpful, thank you! We have a minor request that we're happy to chat through. 

The wording for this is generally "Do we allow duplicate values in columns", and we're wondering if it makes more sense to make it something closer to "does this column allow unique values" i.e more akin to what we'd see if we were thinking of things in a SQL-like manner. Happy to chat this through, lemme know what you think!

2025-05-07 10:06 UTC, Jarek-Rolski commented
I wanted to make naming similar to other variables e.g. "allow_null". I think it could be changed in the future to 'nullable' which is more pydantic.  Is 'unique' acceptable name? 
Another thing I would like to change is how the variable validate data. Now it doesn't validate (False) or drops NA values and checks remaining one (True). I would prefer to have 3 options: "all", "ignore_na" and "False". Do you think this is a good idea and are the options names okay?

2025-05-09 14:49 UTC, MotwaniM commented
Hey Jarek, thanks for raising; think you're point is fair, on reflection allow_duplicates is fine the way it is. For your second point, happy to chat on a call monday; maybe it's best if we merge this in and make your proposed change a new PR?

2025-05-19 17:31 UTC, MotwaniM commented
@Jarek-Rolski closing this!

2025-05-19 17:39 UTC, closed without merging